### ISSUE TITLE
Classnames don't get added to the elements

### ISSUE THREAD

**Issue by karendelakaren** [noeldelgado/gemini-scrollbar#11]
This part seems to be breaking the code for me, it won't add the class names to the elements
```
addClass(this._viewElement.className, [CLASSNAMES.view]);
addClass(this._scrollbarVerticalElement.className, [CLASSNAMES.verticalScrollbar]);
addClass(this._scrollbarHorizontalElement.className, [CLASSNAMES.horizontalScrollbar]);
addClass(this._thumbVerticalElement.className, [CLASSNAMES.thumb]);
addClass(this._thumbHorizontalElement.className, [CLASSNAMES.thumb]);
```
The addClass function doesn't accept a string with spaces ('gm-scrollbar -vertical' and 'gm-scrollbar -horizontal') and it also seems to want the element parameter without .className

**Comment by noeldelgado** [comment]
Thank you @karendelakaren, fixed in 1.2.9.
