### ISSUE TITLE
[REQ] Add scrollTo method?

### ISSUE THREAD

**Issue by Aedaeum** [noeldelgado/gemini-scrollbar#12]
Most, if not all popular scrollbar libraries have a `scrollTo` method that supports pixel positions as well as `top` `bottom` `left` `right` strings. If you can suggest an alternative solution with your current code base, I'd be happy to hear :)

Thanks in advance.

**Comment by tomazzaman** [comment]
+1

**Comment by henrygd** [comment]
In case anyone has a similar problem, you can adjust scroll position using the element returned by the getViewElement method.
```javascript
var scrollElem = yourScrollbarObject.getViewElement();
scrollElem.scrollTop = 42;
scrollElem.scrollLeft = 42;
```

**Comment by noeldelgado** [comment]
Hi everyone, I made a small module just for this, check it out: [pisces](https://github.com/noeldelgado/pisces).

Even if it still as "beta" you can use most of its method without any problem (`scrollToPosition`, `scrollToTop`, `scrollToRight`, `scrollToBottom`, `scrollToLeft`....) or you use any other "scroll-to" library of your preference. At the very end you can find an [example of how you can integrate it with gemini-scrollbar](https://github.com/noeldelgado/pisces#using-it-with-gemini-scrollbar).

Regards.
