### ISSUE TITLE
does this support mobile broswer touch events?

### ISSUE THREAD

**Issue by tianyingchun** [noeldelgado/gemini-scrollbar#13]

**Comment by noeldelgado** [comment]
Hi, did you read the README file? it shouldn't need to support touch events, in that case it should use the native scrollbars and the thing should still work as expected... 

You can access the scrollable-element via `yourInstance.getViewElement()` and subscribe to any event you want/need.

If that doesn't answer your question, can you explain the problem/use-case you are dealing with?

**Comment by tianyingchun** [comment]
yeah. i know your idear.
