### ISSUE TITLE
should add 'selected' class to scrollbars while  dragging the bar

### ISSUE THREAD

**Issue by tianyingchun** [noeldelgado/gemini-scrollbar#14]

**Comment by noeldelgado** [comment]
What's the reason for that? are you trying to set different styles to the thumbs while dragging? if so, you can accomplish it using the `:active` CSS pseudo-class like so:
```css
.gm-scrollbar .thumb:active { /* your custom styles */ }
```

Does this work for you?

**Comment by tianyingchun** [comment]
i will try it.but it may not work on ie9

**Comment by noeldelgado** [comment]
Hum, I was not aware of that, please let me know how it goes, if that does not work I think we can add the class, no big deal. btw, I would rather go for `active` instead of `selected` for the class name.

**Comment by tianyingchun** [comment]
yeah, maybe it need to add 'active' class, sometimes we dragging status, if mouse pointer move out the scrollbar, the `hover`, `:active` effect will lose.

**Comment by noeldelgado** [comment]
Hi, it's been a while but I just tested the `:active` approach on different versions of Windows + IE and now I can confirm that it works ok.

```css
.gm-scrollbar .thumb:active,
.gm-scrollbar .thumb:active { /* your custom styles */ }
```

Tested on:
* Win 10 - Edge
* Win 10 - IE11
* Win 8.1 - IE11
* Win 8 - IE10
* Win 7x64 - IE11
* Win 7x64 - IE10
* Win 7x64 - IE9x64
* Win 7x64 - IE9
* Win 7 - IE9
* Win Vista - IE9

Thanks!
