### ISSUE TITLE
Scrollbar thumb's offset is wrong with a lot of content

### ISSUE THREAD

**Issue by Tarpsvo** [noeldelgado/gemini-scrollbar#34]
Once your content increases to more than ten thousand pixels in length (let's say like 30,000 pixels) and you scroll to the bottom, the scrollbar's thumb will go out of the rail's bounds (I would guess it is the percentages inaccuracy).

I'm horrible at explaining and it's early morning, so just check this sample (scroll to the bottom and watch the vertical thumb).
https://plnkr.co/edit/srL3ikhh1soOrrXDfDND?p=preview

I wonder if it could be fixed using a minimum height/width for the thumbs or if it's related to the actual content based calculations.

**Comment by noeldelgado** [comment]
Hi @Tarpsvo, thanks for the report, I was able to replicate it (on Chrome).

I also noticed that the thumb size can become really really small on large contents, making it almost impossible to interact with, so I think that having a minimum height/width is the way to go. 

I will work on this as soon as I am able.

Thanks!

**Comment by Tarpsvo** [comment]
Hey!

Sorry, I forgot to include my environment variables. :) But yeah, you guessed it, I was using Chrome (for some reason I immediately assumed this would happen for all browsers). 

But yeah, this bug (or missing feature, if I were to blame it on the lack of minimum height), forced me to move on to trying another scrollbar plugin (baron). I'll definitely follow your progress though. Thanks.

**Comment by noeldelgado** [comment]
Thank you!

**Comment by noeldelgado** [comment]
Hi @Tarpsvo, I know we are not using gemini anymore but I want to give you an update regarding this issue.

I just published v1.5.0 which adds the feature to define the minimum size of the thumbs (height for vertical, width for horizontal)... the config option is `minThumbSize` and its default value is `20`(pixels).

Same demo using the new version: https://plnkr.co/edit/Gb5aTCo9eEiY0SkvI5xt?p=preview

I think that fixes the issue so I am closing it now.

Thanks.
