### ISSUE TITLE
TypeError: GeminiScrollbar is not a constructor

### ISSUE THREAD

**Issue by RoboDonut** [noeldelgado/gemini-scrollbar#35]
new to this lib but am having issue getting it in. imports seem to be fine but i am getting constructor error
js
`var myScrollbar = new GeminiScrollbar({
            createElements:false,
            element: document.querySelector('.gm-scrollbar -vertical')
        });
        myScrollbar.create();` 
html
`</div><div id="bigGuy">
            <div id="scrollbar" class="gm-scrollbar -vertical">
                <div class="thumb"></div>
            </div>`

**Comment by noeldelgado** [comment]
> imports seem to be fine

how do you know that? 
how are you loading the lib? (script tag, bundle, etc)
