### ISSUE TITLE
Remove native scrollbar

### ISSUE THREAD

**Issue by artsx** [noeldelgado/gemini-scrollbar#38]
Hello,

There was in the plugin a way to hide all scrollbar default browser?
I would only see the scrollbar components and hide the browser by default, it's possible ?

Best regards,
<img width="243" alt="screen shot 2016-09-22 at 21 00 55" src="https://cloud.githubusercontent.com/assets/7711803/18762088/b04c2a54-8107-11e6-8ed9-39c8a2cb8968.png">

**Comment by noeldelgado** [comment]
Hi @artsx, sorry for the very late response. 

Are you still using this library? if so, could you give me more information about which browser, OS you were using at that time?

The library should hide the browser scrollbars by default.

If you are not using this library anymore, can I close the issue? I am not able to replicate it.

Thanks.

**Comment by artsx** [comment]
Hi @noeldelgado,
 
Yes I always use the plugin, I've added CSS for hide on -webkit- and -moz- the scrollbar and media queries for remove CSS when it's tablet and mobile.

It's ok ! 
Thx

**Comment by noeldelgado** [comment]
Thanks for your response, Arthur, 

just as a side comment, you shouldn't need to add CSS for hiding and showing the scrollbars, in fact, that's what might cause the issue in the first place. I added a note in the README regarding this issue.

> **::-webkit-scrollbar:** If you plan to use gemini-scrollbar on your application I highly recommend you removing any Webkit scrollbar styles you may have, why? using the -webkit- prefixed pseudo-elements will cause Webkit turning off its built-in scrollbar rendering, interfering with our scrollbar-size-check. You can read a bit more about this issue here #1.

Just in case you want to double check if that was indeed the reason.

Thanks
