### ISSUE TITLE
Using Gemini with Electron

### ISSUE THREAD

**Issue by devedge** [noeldelgado/gemini-scrollbar#51]
I'm designing an image viewing application in Electron, and I'm not sure if I'm setting up Gemini incorrectly, or it's simply not the right tool to use.

My app is designed, in part, to display images at 100% size with the application window perfectly proportionally scaled to them. However, the default chromium scrollbar creates a track ~20 pixels wide outside the DOM (# 1), and when I try to restyle it, I can't overlay the scrollbar over the image content. 

Section # 2 is the app with scrollbars disabled, # 3 is the kind of scrollbar style I'd like to use but with the ugly track visible, and # 4 is what I'd like the end result to look like.

![screenshot_20170605_184522](https://cloud.githubusercontent.com/assets/16330401/26806787/b949eb18-4a20-11e7-82bc-3e20f5640a72.png)

Can Gemini overlay the scrollbar over an image element like this? Here's a jsfiddle containing the relevant elements from my app, but it doesn't seem to work (I very likely set it up wrong): https://jsfiddle.net/devedge/fc5ad2fw/

**Comment by noeldelgado** [comment]
hi @devedge, added some CSS to make it work https://jsfiddle.net/4cqbj8c0/9/

**Comment by devedge** [comment]
Thanks! Yes that fixes my issue.
