### ISSUE TITLE
[Question] e.stopImmediatePropagatio() really need?

### ISSUE THREAD

**Issue by vlukyanoff** [noeldelgado/gemini-scrollbar#55]
Hi, @noeldelgado!

I can't use mouseDown event on block with gemini scrollbar because gemini call e.stopImmediatePropagation() in _startDrag function.
I know, stop propagation isn't best practice, because it changes standart behavios of the browser.
Maybe, is there way to avoid stop propogation in this case?

https://github.com/noeldelgado/gemini-scrollbar/blob/88c5d04b24051fb45581bbebe66ad3258ad176d4/index.js#L371

**Comment by noeldelgado** [comment]
Hi @vlukyanoff, did #56 fix the issue? (v1.5.3)

**Comment by vlukyanoff** [comment]
Hi @noeldelgado! Yes, it fixed the issue. Thank you!

**Comment by vlukyanoff** [comment]
@noeldelgado, could you update dependency in https://github.com/noeldelgado/react-gemini-scrollbar please?

**Comment by Guria** [comment]
I would be great if gemini-scrollbar were peerDependency of react-gemini-scrollbar to avoid such update needs.

**Comment by noeldelgado** [comment]
@vlukyanoff done, thanks!
