### ISSUE TITLE
Chrome 62 not working for me, Firefox 57 ok

### ISSUE THREAD

**Issue by frumbert** [noeldelgado/gemini-scrollbar#57]
I noticed chrome updated a few days ago to version 62(Version 62.0.3202.94 Official Build 64-bit, osx 10.12.6) and the scrolling seems to have stopped for me. Here I am scrolling up and down the page but the scrollbar won't activate. I can select text within the scrolling area, so I don't think it's a focus issue.

![screencap-chrome](https://user-images.githubusercontent.com/592257/33002873-ff77321c-ce0a-11e7-9203-d53fb99c2849.gif)

I also noticed firefox updated to version 57 and that works just fine.

![screencap-firefox](https://user-images.githubusercontent.com/592257/33002875-02430502-ce0b-11e7-9532-2f3e976c4c0a.gif)

I've found this to be fairly consistent, though once chrome DID start scrolling, I refreshed and it had stopped again and I can't figure out why.

**Comment by noeldelgado** [comment]
Thanks for the report @frumbert! 🙌 
I just checked and found an issue on my end, gh-page should be fixed now. 👍
