### ISSUE TITLE
onUpdate callback - request

### ISSUE THREAD

**Issue by flexphperia** [noeldelgado/gemini-scrollbar#6]
How to track scroll position on user interaction?
I'd would be nice to have callback passed to options called everytime position changes.

**Comment by noeldelgado** [comment]
Hi @flexphperia, you can subscribe to the scroll event if you need it like so:

```js
var instance = new GeminiScrollbar({
    element: document.querySelector(‘.something’)
}).create();

function scrollTest(ev) {console.log(ev.target.scrollTop);};
instance.getViewElement().addEventListener('scroll', scrollTest);
```

Let me know if that works for you.

**Comment by flexphperia** [comment]
Yeah I know that should work but when you attach event listener using jquery:
```$('div').scroll(function(){   });``` 
 it not work so I modified plugin to have callback ```onScroll```

**Comment by noeldelgado** [comment]
You can still attach the event using jquery after running the `create` method:

```js
instance.create();
$(instance.getViewElement()).scroll(function() { });
```

That should work as expected.

**Comment by flexphperia** [comment]
As I remember it was not working.

**Comment by noeldelgado** [comment]
Weird, it works for me, [check out this bin](http://jsbin.com/qaraxokota/edit?js,output)

I think the key is that you need to call the `create` method before binding.

**Comment by flexphperia** [comment]
Works fine, thanks.
