### ISSUE TITLE
support for scrollbars that are not full client size - proposition

### ISSUE THREAD

**Issue by flexphperia** [noeldelgado/gemini-scrollbar#9]
Now plugin does not support scrollbar width/height that is smaller than clientWidth/clientHeight.

Replace ```_mouseMoveDocumentHandler``` method with this:
```
GeminiScrollbar.prototype._mouseMoveDocumentHandler = function(e) {
	if (this._cursorDown === false) {
		return;
	}

	var offset, thumbClickPosition, thumbPositionPercentage; 

	if (this._prevPageY) {
		offset = ((this._scrollbarVerticalElement.getBoundingClientRect().top - e.clientY) * -1);
		thumbClickPosition = (this._thumbVerticalElement.offsetHeight - this._prevPageY);
		thumbPositionPercentage = ((offset - thumbClickPosition) * 100 / this._scrollbarVerticalElement.offsetHeight); //CHANGE

		this._viewElement.scrollTop = (thumbPositionPercentage * this._viewElement.scrollHeight / 100);
		
		return;
	}

	if (this._prevPageX) {
		offset = ((this._scrollbarHorizontalElement.getBoundingClientRect().left - e.clientX) * -1); 
		thumbClickPosition = (this._thumbHorizontalElement.offsetWidth - this._prevPageX);
		thumbPositionPercentage = ((offset - thumbClickPosition) * 100 / this._scrollbarHorizontalElement.offsetWidth); //CHANGE

		this._viewElement.scrollLeft = (thumbPositionPercentage * this._viewElement.scrollWidth / 100);
	}
};
```

**Comment by flexphperia** [comment]
noeldelgado, can you review this change?
It works fine, but sometimes (on different scroll sizes) thumb do not touch end border of scrollbar when scrolled to end.

**Comment by noeldelgado** [comment]
You are right, I just tried and I can confirm. This also happens if you put some offsets for the `gm-scrollbar -vertical` and/or `gm-scrollbar -horizonta` elements. e.g. `top: 20px; bottom: 20px`.

I also found that the `_clickVerticalTrackHandler` and `_clickHorizontalTrackHandler` methods will need to be fixed as well.

Changing
```js
var thumbPositionPercentage = ((offset - thumbHalf) * 100 / this._viewElement.clientHeight);
// to
var thumbPositionPercentage = ((offset - thumbHalf) * 100 / this._scrollbarVerticalElement.offsetHeight);
```

and 

```js
var thumbPositionPercentage = ((offset - thumbHalf) * 100 / this._viewElement.clientWidth);
// to
var thumbPositionPercentage = ((offset - thumbHalf) * 100 / this._scrollbarHorizontalElement.offsetWidth);

```

Do you want to do the PR? otherwise I can take it.

thanks!

**Comment by flexphperia** [comment]
Thanks. Sorry I dont know what is "PR" so better you do it :)

**Comment by noeldelgado** [comment]
PR = Pull Request

How you ever going into the process of forking and contributing to a project before?

If you want to do it I and more happy to assist you in any way I can, you can contact me via email if you want (pixelia.me@gmail.com).

If you do not feel like doing it right now, no problem, I just think it could be a good chance in case you haven't done it before :)

**Comment by flexphperia** [comment]
Thanks but I'm only commenting and submiting bugs. I'm fine with this for now. I have own something like repository when I collect plugins with changes made by me :)

**Comment by noeldelgado** [comment]
Ok, cool :+1:
